// SPDX-License-Identifier: GPL-3.0-or-later
//! License and attribution, checked rather than remembered.
//!
//! # What is actually being distributed
//!
//! `src/data/pm7*.csv` are generated from a pinned MOPAC v23.2.5 checkout (Apache-2.0, © 2021
//! Virginia Tech) by `tools/extract_params/extract_pm7.py`, and they are pulled into the binary
//! with `include_str!`. So the compiled artifacts -- the crate, and the `_native.pyd` inside the
//! Python wheel -- **contain** Apache-2.0-derived material, and distributing them is a
//! redistribution under that license. Apache-2.0 §4(a) requires giving every recipient a copy of
//! the License; §4(b) requires the derivative to carry the attribution notices.
//!
//! That is a packaging fact, not a source-tree fact, and packaging is exactly the kind of thing
//! that decays silently: a file gets moved, a `license-files` entry is not updated, and the wheel
//! ships without the notice while every test still passes. Through 0.2.2 `third_party/` held a
//! BSD-3-Clause license for PySEQM that `pyproject.toml` never listed, so it reached no wheel at
//! all. Replacing it with the MOPAC license in 0.2.3 fixed the *right* license being present and
//! left the same hole until this file was written.
//!
//! # The layer above that
//!
//! The same argument runs one level up and is easier to miss, because no source file records it.
//! `cargo build` links statically, so both shipped binaries are copies of a substantial portion of
//! every crate in the graph -- around 120 of them, MIT or Apache-2.0 almost throughout. MIT asks
//! for its notice in "all copies or substantial portions"; Apache-2.0 asks by §4(a) and §4(b).
//! Through 0.2.2 neither binary carried any of it.
//!
//! `third_party/rust/NOTICES.md` is generated by `tools/licenses/collect_rust_notices.py` from the
//! resolved graph. A generated file rots exactly as fast as an editor forgets to regenerate it, so
//! `every_linked_crate_has_a_notice` walks `Cargo.lock` independently and fails when a new
//! dependency arrives without one.
//!
//! These tests are cheap, need no SCF, and fail the moment the chain breaks.

use std::path::{Path, PathBuf};

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn read(relative: &str) -> String {
    let path = root().join(relative);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
}

/// The MOPAC license text is present, and is the license it claims to be.
#[test]
fn the_mopac_license_is_in_the_tree() {
    let text = read("third_party/mopac/LICENSE");
    assert!(
        text.contains("Apache License") && text.contains("Version 2.0"),
        "third_party/mopac/LICENSE is not the Apache 2.0 text"
    );
    assert!(
        text.contains("Redistribution"),
        "the license text looks truncated"
    );
}

/// The notices name the license file, so a reader can get from one to the other.
#[test]
fn the_notices_point_at_the_license_they_rely_on() {
    let notices = read("THIRD_PARTY_NOTICES.md");
    assert!(
        notices.contains("third_party/mopac/LICENSE"),
        "THIRD_PARTY_NOTICES.md must name the license file it relies on"
    );
    assert!(
        notices.contains("Apache-2.0") && notices.contains("MOPAC"),
        "the notices must name the upstream and its license"
    );
    // The PySEQM notice was removed in 0.2.3 along with its license file. If one comes back
    // without the other, this catches it.
    let orphaned = notices.contains("third_party/pyseqm");
    assert!(
        !orphaned || root().join("third_party/pyseqm/LICENSE").exists(),
        "THIRD_PARTY_NOTICES.md points at a license file that is not in the tree"
    );
}

/// **The packaging check.** Every license file in the tree must be listed in `license-files`, or
/// the wheel ships without it.
///
/// This is the one that would have caught the gap. `pyproject.toml` listed `LICENSE` and
/// `THIRD_PARTY_NOTICES.md` and not the Apache text, so a `pip install pm7-rs-python` delivered a
/// binary containing MOPAC-derived tables with no copy of the MOPAC license anywhere in it.
#[test]
fn every_license_file_reaches_the_wheel() {
    let listed = license_files_entry();

    let mut missing = Vec::new();
    let third_party = root().join("third_party");
    if third_party.is_dir() {
        collect_licenses(&third_party, &mut |path| {
            let relative = path
                .strip_prefix(root())
                .expect("under the manifest directory")
                .to_string_lossy()
                .replace('\\', "/");
            if !listed.contains(&relative) {
                missing.push(relative);
            }
        });
    }
    assert!(
        missing.is_empty(),
        "these license files are in the tree but not in `license-files`, so they never reach the \
         wheel: {missing:?}\n  license-files = {listed}"
    );
}

/// The value of `license-files` in `pyproject.toml`, however it is spelled.
///
/// It was one line until the Rust notice was added and is an array over several now, so reading
/// "the line that starts with `license-files`" stopped seeing most of it. Take everything from the
/// key to the closing bracket.
fn license_files_entry() -> String {
    let pyproject = read("pyproject.toml");
    let start = pyproject
        .find("\nlicense-files")
        .expect("pyproject.toml must declare license-files");
    let rest = &pyproject[start + 1..];
    let end = rest.find(']').map(|i| i + 1).unwrap_or_else(|| {
        rest.find('\n').unwrap_or(rest.len()) // a single-line, non-array spelling
    });
    rest[..end].to_string()
}

fn collect_licenses(directory: &Path, found: &mut impl FnMut(&Path)) {
    let Ok(entries) = std::fs::read_dir(directory) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_licenses(&path, found);
        } else if path
            .file_name()
            .and_then(|n| n.to_str())
            // `NOTICE` is here for `third_party/rust/NOTICES.md`, which carries license texts and
            // has to reach the wheel for the same reason a `LICENSE` file does.
            .map(|n| {
                n.starts_with("LICENSE") || n.starts_with("COPYING") || n.starts_with("NOTICE")
            })
            .unwrap_or(false)
        {
            found(&path);
        }
    }
}

/// **Every crate linked into a shipped binary has a notice.**
///
/// `third_party/rust/NOTICES.md` is generated, and a generated file is only as current as the last
/// person to remember to regenerate it. So this walks `Cargo.lock` from the root package instead
/// and checks the result against the notice, which means adding a dependency and shipping without
/// its notice is a test failure rather than a thing to notice at release time.
///
/// The walk skips the `[dev-dependencies]` roots declared in `Cargo.toml`. That distinction is the
/// whole point: `Cargo.lock` has 153 packages and only 117 are in any released artifact. The other
/// 36 -- `criterion` and its tree, which is where `serde`, `serde_json` and `clap` come from -- are
/// linked into `benches/scaling.rs` and nothing that leaves this machine. A crate reachable both
/// through a dev dependency *and* a real one is still required, because the walk reaches it by the
/// real path.
#[test]
fn every_linked_crate_has_a_notice() {
    let notices = read("third_party/rust/NOTICES.md");
    let lock = read("Cargo.lock");
    let packages = lock_packages(&lock);

    let root = "pm7-rs";
    let dev_roots = dev_dependency_names();
    assert!(
        !dev_roots.is_empty(),
        "no [dev-dependencies] found in Cargo.toml -- the parser is looking at the wrong thing"
    );

    let mut reachable: Vec<&str> = Vec::new();
    let mut stack = vec![root];
    while let Some(name) = stack.pop() {
        if reachable.contains(&name) {
            continue;
        }
        reachable.push(name);
        for (package, dependencies) in &packages {
            if *package != name {
                continue;
            }
            for dependency in dependencies {
                if !dev_roots.iter().any(|d| d == dependency) {
                    stack.push(dependency);
                }
            }
        }
    }

    let mut missing: Vec<&str> = reachable
        .iter()
        .copied()
        .filter(|name| *name != root)
        // The table rows are `| crate | version | license | copyright |`.
        .filter(|name| !notices.contains(&format!("| {name} | ")))
        .collect();
    missing.sort_unstable();
    assert!(
        missing.is_empty(),
        "these crates are linked into the shipped binaries but have no entry in \
         third_party/rust/NOTICES.md: {missing:?}\n  \
         run `python tools/licenses/collect_rust_notices.py`"
    );
}

/// The notice carries license *texts*, not just a table of SPDX identifiers.
///
/// A table of identifiers is a bibliography; MIT and Apache-2.0 both ask for the text. The MPL
/// assertion is the one worth pinning: `faer`'s manifest declares `MIT` and the crate additionally
/// ships four files for algorithms ported from Eigen, LAPACK and SuiteSparse. A generator that
/// trusted the SPDX field would drop them, and nothing else in the tree would notice.
#[test]
fn the_rust_notices_carry_the_license_texts() {
    let notices = read("third_party/rust/NOTICES.md");
    assert!(
        notices.contains("Permission is hereby granted, free of charge"),
        "the MIT text is missing from third_party/rust/NOTICES.md"
    );
    assert!(
        notices.contains("Apache License") && notices.contains("Version 2.0"),
        "the Apache-2.0 text is missing from third_party/rust/NOTICES.md"
    );
    assert!(
        notices.contains("COPYING.EIGEN.MPL2"),
        "faer's ported-algorithm licenses are missing -- the generator is reading the SPDX field \
         rather than the crate's own license files"
    );
    for crate_name in ["faer", "rayon", "pyo3", "libm"] {
        assert!(
            notices.contains(&format!("| {crate_name} | ")),
            "{crate_name} is missing from the notice table"
        );
    }
}

/// `(name, dependency names)` for every `[[package]]` in a `Cargo.lock`.
///
/// A dependency entry is `"name"`, or `"name version"` when the lock holds more than one version;
/// only the name is needed here, since the notice is keyed by name and lists every version.
fn lock_packages(lock: &str) -> Vec<(&str, Vec<&str>)> {
    let mut packages = Vec::new();
    for block in lock.split("[[package]]").skip(1) {
        let Some(name) = toml_string(block, "name") else {
            continue;
        };
        let mut dependencies = Vec::new();
        if let Some(start) = block.find("dependencies = [") {
            let rest = &block[start..];
            if let Some(end) = rest.find(']') {
                for line in rest[..end].lines().skip(1) {
                    if let Some(entry) = line.trim().trim_end_matches(',').strip_prefix('"') {
                        let entry = entry.trim_end_matches('"');
                        dependencies.push(entry.split(' ').next().unwrap_or(entry));
                    }
                }
            }
        }
        packages.push((name, dependencies));
    }
    packages
}

/// The names under `[dev-dependencies]` in `Cargo.toml`.
fn dev_dependency_names() -> Vec<String> {
    let manifest = read("Cargo.toml");
    let Some(start) = manifest.find("[dev-dependencies]") else {
        return Vec::new();
    };
    let section = &manifest[start + "[dev-dependencies]".len()..];
    let end = section.find("\n[").unwrap_or(section.len());
    section[..end]
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                return None;
            }
            line.split('=').next().map(|n| n.trim().to_string())
        })
        .filter(|n| !n.is_empty())
        .collect()
}

fn toml_string<'a>(block: &'a str, key: &str) -> Option<&'a str> {
    block.lines().find_map(|line| {
        let rest = line
            .trim()
            .strip_prefix(key)?
            .trim_start()
            .strip_prefix('=')?;
        rest.trim().strip_prefix('"')?.strip_suffix('"')
    })
}

/// Every source file carries an SPDX identifier.
///
/// Not decoration: it is what tells a downstream packager, and every automated license scanner,
/// what each file is under. `tools/extract_params/extract_pm7.py` -- the script that derives the
/// parameter tables from MOPAC, and so the most attribution-sensitive file in the repository --
/// was missing one until 0.2.3.
#[test]
fn every_source_file_declares_its_license() {
    let mut missing = Vec::new();
    for directory in ["src", "tests", "tools", "python", "benches", "examples"] {
        let path = root().join(directory);
        if path.is_dir() {
            check_spdx(&path, &mut missing);
        }
    }
    assert!(
        missing.is_empty(),
        "these source files have no SPDX-License-Identifier: {missing:?}"
    );
}

fn check_spdx(directory: &Path, missing: &mut Vec<String>) {
    let Ok(entries) = std::fs::read_dir(directory) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        // Generated, vendored or cache directories are not ours to annotate.
        if path.is_dir() {
            if !matches!(
                name,
                "__pycache__" | "target" | "oracle" | "mopac-23.2.5-win"
            ) {
                check_spdx(&path, missing);
            }
            continue;
        }
        let extension = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        if !matches!(extension, "rs" | "py") {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue;
        };
        // The identifier belongs at the top; scanning the first few lines keeps a stray mention
        // deep in a doc comment from counting.
        let head: String = text.lines().take(5).collect::<Vec<_>>().join("\n");
        if !head.contains("SPDX-License-Identifier") {
            missing.push(
                path.strip_prefix(root())
                    .unwrap_or(&path)
                    .to_string_lossy()
                    .replace('\\', "/"),
            );
        }
    }
}
