#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate src/mndod_tables.rs from MOPAC's mndod.F90 `fordd` + mndod_C.F90.

These are the geometry-independent index / multipole-coefficient tables of the
MNDO/d two-center kernel (ind2, isym, ch, indpp, inddp, inddd). Mechanically
transcribing them from the Fortran avoids hand-copy errors across ~1000 entries.

Provenance: MOPAC v23.2.5, Apache-2.0 (c) 2021 Virginia Tech.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MNDOD = ROOT / ".mopac-source" / "src" / "integrals" / "mndod.F90"
MNDOD_C = ROOT / ".mopac-source" / "src" / "integrals" / "mndod_C.F90"
OUT = ROOT / "src" / "mndod_tables.rs"


def read_data_array(text: str, name: str) -> list:
    """Parse a Fortran `data <name>/ v1, v2, ... /` block into a list of ints."""
    m = re.search(r"data\s+" + name + r"\s*/(.*?)/", text, re.S | re.I)
    if not m:
        sys.exit(f"data {name} not found")
    body = m.group(1)
    return [int(tok) for tok in re.findall(r"-?\d+", body)]


def fortran_float(tok: str) -> float:
    return float(tok.strip().replace("D", "E").replace("d", "E"))


def read_fordd(text: str) -> str:
    # Grab the body of `subroutine fordd ... end subroutine fordd`.
    m = re.search(r"subroutine fordd\b(.*?)end subroutine fordd", text, re.S)
    if not m:
        sys.exit("fordd subroutine not found")
    return m.group(1)


def main() -> None:
    text = MNDOD.read_text()
    body = read_fordd(text)

    # ind2(i,j) = k   -> flat [45*45] row-major (i-1)*45+(j-1)
    ind2 = [0] * (45 * 45)
    for i, j, k in re.findall(r"ind2\(\s*(\d+)\s*,\s*(\d+)\s*\)\s*=\s*(\d+)", body):
        ind2[(int(i) - 1) * 45 + (int(j) - 1)] = int(k)

    # isym(i) = v  (v may be negative)
    isym = [0] * 492  # 1-based, indices 1..491
    for i, v in re.findall(r"isym\(\s*(\d+)\s*\)\s*=\s*(-?\d+)", body):
        isym[int(i)] = int(v)

    # ch(i,l,m) = val ; i 1..45, l 0..2, m -2..2. Store flat [45][3][5] with m+2.
    ch = [0.0] * (45 * 3 * 5)
    ch_re = re.compile(r"ch\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(-?\d+)\s*\)\s*=\s*([-.\dD]+)")
    for i, l, m, val in ch_re.findall(body):
        i, l, m = int(i), int(l), int(m)
        ch[((i - 1) * 3 + l) * 5 + (m + 2)] = fortran_float(val)

    def small(name):
        pat = re.compile(name + r"\(\s*(\d+)\s*,\s*(\d+)\s*\)\s*=\s*(\d+)")
        return pat.findall(body)

    indpp = [0] * 9  # (3,3) row-major (i-1)*3+(j-1)
    for i, j, k in small("indpp"):
        indpp[(int(i) - 1) * 3 + (int(j) - 1)] = int(k)
    inddp = [0] * 15  # (5,3)
    for i, j, k in small("inddp"):
        inddp[(int(i) - 1) * 3 + (int(j) - 1)] = int(k)
    inddd = [0] * 25  # (5,5)
    for i, j, k in small("inddd"):
        inddd[(int(i) - 1) * 5 + (int(j) - 1)] = int(k)

    # One-center integral index maps (mndod_C.F90), 243 entries each.
    ctext = MNDOD_C.read_text()
    intij = read_data_array(ctext, "intij")
    intkl = read_data_array(ctext, "intkl")
    intrep = read_data_array(ctext, "intrep")
    if not (len(intij) == len(intkl) == len(intrep) == 243):
        sys.exit(f"int* length mismatch: {len(intij)},{len(intkl)},{len(intrep)}")

    def fmt_ints(vals, per=20):
        out = []
        for i in range(0, len(vals), per):
            out.append("    " + ", ".join(str(v) for v in vals[i : i + per]) + ",")
        return "\n".join(out)

    def fmt_floats(vals, per=8):
        out = []
        for i in range(0, len(vals), per):
            out.append("    " + ", ".join(f"{v:.8}" for v in vals[i : i + per]) + ",")
        return "\n".join(out)

    with OUT.open("w", newline="\n") as f:
        f.write(
            "// SPDX-License-Identifier: GPL-3.0-or-later\n"
            "// GENERATED by tools/extract_params/gen_mndod_tables.py from MOPAC\n"
            "// v23.2.5 src/integrals/mndod.F90 `fordd`. Do not edit by hand.\n"
            "// Provenance: MOPAC, Apache-2.0 (c) 2021 Virginia Tech.\n\n"
            "//! MNDO/d index and multipole-coefficient tables (geometry-independent).\n\n"
        )
        f.write(
            "/// `ind2[(ij-1)*45 + (kl-1)]` = local integral slot (1..491), 0 if none.\n"
            f"pub static IND2: [u16; {45*45}] = [\n{fmt_ints(ind2)}\n];\n\n"
        )
        f.write(
            "/// `ISYM[n]` symmetry map for local integral slot n (1..491); may be negative.\n"
            f"pub static ISYM: [i16; 492] = [\n{fmt_ints(isym)}\n];\n\n"
        )
        f.write(
            "/// `CH[((i-1)*3 + l)*5 + (m+2)]` multipole coefficient, i 1..45, l 0..2, m -2..2.\n"
            f"pub static CH: [f64; {45*3*5}] = [\n{fmt_floats(ch)}\n];\n\n"
        )
        f.write(
            "/// `INDPP[(i-1)*3 + (j-1)]` (3x3).\n"
            f"pub static INDPP: [u8; 9] = [\n{fmt_ints(indpp)}\n];\n\n"
        )
        f.write(
            "/// `INDDP[(i-1)*3 + (j-1)]` (5x3).\n"
            f"pub static INDDP: [u8; 15] = [\n{fmt_ints(inddp)}\n];\n\n"
        )
        f.write(
            "/// `INDDD[(i-1)*5 + (j-1)]` (5x5).\n"
            f"pub static INDDD: [u8; 25] = [\n{fmt_ints(inddd)}\n];\n\n"
        )
        f.write(
            "/// One-center spd integral maps (MOPAC wstore): w(INTIJ[i], INTKL[i]) = repd[INTREP[i]].\n"
            f"pub static INTIJ: [u8; 243] = [\n{fmt_ints(intij)}\n];\n\n"
            f"pub static INTKL: [u8; 243] = [\n{fmt_ints(intkl)}\n];\n\n"
            f"pub static INTREP: [u8; 243] = [\n{fmt_ints(intrep)}\n];\n"
        )

    nz_ind2 = sum(1 for v in ind2 if v)
    nz_isym = sum(1 for v in isym if v)
    nz_ch = sum(1 for v in ch if v)
    print(f"wrote {OUT}")
    print(f"  ind2 nonzero = {nz_ind2} (expect 491)")
    print(f"  isym nonzero = {nz_isym}")
    print(f"  ch nonzero   = {nz_ch}")
    print(f"  max ind2     = {max(ind2)} (expect 491)")


if __name__ == "__main__":
    main()
