# SPDX-License-Identifier: GPL-3.0-or-later
"""Build the source release archive.

    python tools/make_release_zip.py [--out DIR] [--verify]

The archive is the development tree minus the things that are either regenerable, enormous, or not
ours to redistribute:

* ``target/`` and ``dist/`` — build output, 4 GB of it;
* ``.git/`` — history belongs in the repository, not in a source drop;
* ``.mopac-source/`` (87 MB) and ``tools/oracle/mopac-23.2.5-win/`` (37 MB) — a pinned MOPAC
  source tree and a vendored MOPAC build. They are Apache-2.0, they are used only for the fidelity
  audit and the oracle, and `Cargo.toml` already excludes them from the published crate. The
  oracle *scripts* stay; they find MOPAC from ``$MOPAC_EXE`` or ``PATH``;
* oracle scratch directories, ``__pycache__``, and compiled Python artifacts.

``--verify`` unpacks the result somewhere with no repository around it and runs ``cargo check`` on
it. That is the check that matters: the parameter CSVs are compiled in with ``include_str!``, so a
missing ``src/data`` file is a build failure for whoever unpacks it, and the person who made the
archive is the last to find out.

The file list comes from ``git ls-files``, not from walking the tree. Walking ships whatever
happens to be on disk, which is the wrong set in both directions: the 0.2.1 archive carried
``src/variant.rs``, deleted six commits earlier, and it *would* have carried an uncommitted
``src/molden.rs`` while a clean clone of the same revision did not compile at all. The tracked set
is by definition what someone cloning gets, so building from it makes the archive and the
repository the same thing. A dirty tree is refused rather than silently resolved, because "which
version is in this zip" has to have one answer; ``--allow-dirty`` overrides for a deliberate
local drop.
"""

from __future__ import annotations

import argparse
import pathlib
import shutil
import subprocess
import sys
import tempfile
import tomllib
import zipfile

ROOT = pathlib.Path(__file__).resolve().parents[1]

EXCLUDED_DIRS = {
    ".git",
    ".github/workflows/.cache",
    ".mopac-source",
    ".pytest_cache",
    "__pycache__",
    "dist",
    "target",
    "tools/oracle/mopac-23.2.5-win",
    # Oracle working directories: regenerated by the scripts, and full of MOPAC output.
    "tools/oracle/cases",
    "tools/oracle/dcases",
    "tools/oracle/hbcases",
    "tools/oracle/pairsweep",
    "tools/oracle/scfres",
}

EXCLUDED_SUFFIXES = {".pyc", ".pyd", ".so", ".dylib", ".zip", ".whl"}


def version() -> str:
    with (ROOT / "Cargo.toml").open("rb") as handle:
        return tomllib.load(handle)["package"]["version"]


def included(path: pathlib.Path) -> bool:
    relative = path.relative_to(ROOT).as_posix()
    for excluded in EXCLUDED_DIRS:
        if relative == excluded or relative.startswith(excluded + "/"):
            return False
    return path.suffix.lower() not in EXCLUDED_SUFFIXES


def git(*arguments: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(ROOT), *arguments], capture_output=True, text=True, check=False
    )


def tracked_files() -> list[pathlib.Path] | None:
    """The paths ``git`` knows about, or ``None`` if this is not a usable checkout."""
    if shutil.which("git") is None or not (ROOT / ".git").exists():
        return None
    done = git("ls-files", "-z")
    if done.returncode != 0:
        return None
    names = [name for name in done.stdout.split("\0") if name]
    # A tracked path can still be absent from disk (a deletion staged but not committed). Ship what
    # is actually there; `dirty()` is what refuses that situation in the first place.
    return [ROOT / name for name in names if (ROOT / name).is_file()]


def dirty() -> list[str]:
    done = git("status", "--porcelain", "--untracked-files=normal")
    if done.returncode != 0:
        return []
    return [line for line in done.stdout.splitlines() if line.strip()]


def collect(allow_dirty: bool) -> list[pathlib.Path]:
    files = tracked_files()
    if files is None:
        print("not a git checkout; falling back to a tree walk", file=sys.stderr)
        files = [p for p in ROOT.rglob("*") if p.is_file()]
    else:
        changes = dirty()
        if changes and not allow_dirty:
            listing = "\n  ".join(changes[:20])
            more = f"\n  ... and {len(changes) - 20} more" if len(changes) > 20 else ""
            raise SystemExit(
                "the working tree has uncommitted changes, so the archive would not correspond to "
                f"any revision:\n  {listing}{more}\n"
                "Commit them, or pass --allow-dirty to archive the tracked files as they stand."
            )
    files = [p for p in files if included(p)]
    return sorted(files, key=lambda p: p.relative_to(ROOT).as_posix())


def build(out_dir: pathlib.Path, allow_dirty: bool) -> pathlib.Path:
    name = f"pm7-rs-{version()}"
    out_dir.mkdir(parents=True, exist_ok=True)
    archive = out_dir / f"{name}.zip"
    files = collect(allow_dirty)
    # Deflate rather than store: this is text, and the difference is a factor of four.
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for path in files:
            zf.write(path, f"{name}/{path.relative_to(ROOT).as_posix()}")
    size_mb = archive.stat().st_size / (1024 * 1024)
    print(f"{archive}  ({len(files)} files, {size_mb:.1f} MB)")
    return archive


def verify(archive: pathlib.Path) -> int:
    """Unpack somewhere isolated and make sure it builds from its own contents alone."""
    with tempfile.TemporaryDirectory() as tmp:
        root = pathlib.Path(tmp)
        with zipfile.ZipFile(archive) as zf:
            zf.extractall(root)
        unpacked = next(root.iterdir())
        missing = [
            required
            for required in ("Cargo.toml", "src/data", "src/lib.rs", "python/pm7_rs/__main__.py")
            if not (unpacked / required).exists()
        ]
        if missing:
            print(f"missing from the archive: {', '.join(missing)}", file=sys.stderr)
            return 1
        print(f"verifying {unpacked} with cargo check ...")
        done = subprocess.run(
            ["cargo", "check", "--all-targets", "--locked"],
            cwd=unpacked,
            capture_output=True,
            text=True,
        )
        if done.returncode != 0:
            print(done.stderr[-4000:], file=sys.stderr)
            return done.returncode
        print("the archive builds from its own contents")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(ROOT / "dist"), help="output directory")
    parser.add_argument(
        "--verify",
        action="store_true",
        help="unpack into a scratch directory and run `cargo check` there",
    )
    parser.add_argument(
        "--allow-dirty",
        action="store_true",
        help="archive the tracked files even though the working tree has uncommitted changes",
    )
    args = parser.parse_args()
    if shutil.which("cargo") is None and args.verify:
        print("cargo is not on PATH, so --verify cannot run", file=sys.stderr)
        return 1
    archive = build(pathlib.Path(args.out), args.allow_dirty)
    return verify(archive) if args.verify else 0


if __name__ == "__main__":
    raise SystemExit(main())
